latest_avatar_size:
  default: small
  type: enum
  choices:
    - tiny
    - small
    - medium
    - large
    - extra_large
    - huge
topic_avatars_size:
  default: 45
  type: enum
  choices:
    - 45
    - 60
    - 70
    - 80
    - 90
    - 100
    - 120
    - 140
    - 160
    - 180
    - 200
header_avatars_size:
  default: 32
  type: enum
  choices:
    - 45
    - 60
    - 70
    - 80
    - 90
header_height:
  default: 60
  type: enum
  choices:
    - 70
    - 80
    - 90
    - 100
margin_top:
  default: 0
  type: string
avatars_border_radius:
  default: 50%
  type: enum
  choices:
    - 0%
    - 10%
    - 20%
    - 30%
    - 40%
mobile_avatars_size:
  default: 45
  min: 45
  max: 80
